project:
  type: website
  output-dir: docs

website:
  title: "Mary Kreklow"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: FinalProject.qmd
        text: MSCS 164
      - sidebar:DS2
      - file: SDS272.qmd
        text: SDS 272
      - file: ChallengeOne.qmd
        text: SDS 341
      - sidebar:ECON


  sidebar:
    - id: DS2
      title: "MSCS 264"
      contents:
        - us_states.qmd
        - rtip.qmd
        - mini_project2.qmd
        - RATATOUILLE.qmd
    - id: ECON
      title: "Econ"
      contents:
        - ECON385.qmd
        - ECON372.qmd


  page-footer:
    left: |
      &copy; Mary Kreklow, 2026<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual


